import { Tool } from "./tool"
import z from "zod"
import { Session } from "../session"

/**
 * task_done - Signals that a dual-pair session has completed successfully
 *
 * Only available to discriminator agent in dual-pair sessions.
 * When called, marks the session as complete and exits the dual-pair loop.
 * A detailed summary will be generated via LLM call after completion.
 */
export const TaskDoneTool = Tool.define("task_done", async () => {
  return {
    description: `Signal that the task is complete and satisfactory. Use this when all requirements are met, tests pass, and code quality is good.`,
    parameters: z.object({
      ready: z.literal(true).describe("Confirm the task is complete"),
    }),
    async execute(params, ctx) {
      // Just mark completion - summary will be generated by dual-pair via LLM call
      await Session.update(ctx.sessionID, (session) => {
        ;(session.metadata as any).dualPairComplete = true
        ;(session.metadata as any).completedAt = Date.now()
      })

      return {
        title: "Task Complete",
        metadata: {},
        output: "Task marked as complete. Summary will be generated.",
      }
    },
  }
})
